### ISSUE TITLE
Find augeas replacement for Windows code

### ISSUE THREAD

**Issue by iversond** [psadmin-io/psadminio-io_weblogic#6]
The cookiename change is done via augeas, which is not supported on Windows. A `file_line` resource could be used instead.

**Comment by iversond** [comment]
Possible solution: https://gist.github.com/spuder/28c462e2e4eb651db5d2#file-xmlmodify-ps1%3C/p%3E

Use `augeas.ps1` with the powershell `exec` type to modify the file for Windows servers.

**Comment by ericbisme** [comment]
Closing here. Added Windows option using file_line in the io_portalwar module. It may not be as future-proof as the Augeas version, but it should be good for the current versions of PeopleTools.

I am shying away from the powershell version to avoid asking users to t let us place the script somewhere on their Windows server. I could be convinced otherwise if the Windows PeopleSoft contingent prefers that option.

Let's have that discussion on the io_portalwar repo as needed.
